filter:
  paths: [src/*]
  excluded_paths: [vendor/*, test/*]
before_commands:
  - 'composer install --dev'
tools:
  external_code_coverage: 
    timeout: 300
  php_mess_detector: true
  php_code_sniffer: true
  sensiolabs_security_checker: true
  php_code_coverage: true
  php_pdepend: true
  php_loc:
    enabled: true
    excluded_dirs: [vendor, tests]
  php_cpd:
    enabled: false
    excluded_dirs: [vendor, tests]
  php_sim: true
  php_changetracking: true
  php_cs_fixer: true
  php_analyzer: true
  sensiolabs_security_checker: true
checks:
  php:
    code_rating: true
    duplication: true

