language: php

php:
  - 5.5
    
before_script:
  - composer install

script:
  - mkdir -p build/logs
  - vendor/bin/phpunit -c app --coverage-clover build/logs/clover.xml

after_script:
  - php vendor/bin/coveralls -v

