services:
  app:
    class: Symfony\Component\Console\Application
    calls:
      - [ add, ["@LocationCommand"]]
  LocationCommand:
    class: Nachinius\Command\LocationCommand
    arguments: ["@HtmlGetter"]
  HtmlGetter:
    class: Nachinius\Command\Components\HtmlGetter
    arguments: ["@HttpGetter","@cache"]
  HttpGetter:
    class: Nachinius\Command\Components\HttpGetter
  cache:
    class: Nachinius\Command\Components\Cache
    arguments: ["%app.root_dir%/../data","@fs"]
  fs:
    class: Symfony\Component\Filesystem\Filesystem
