services:
  app:
    class: Symfony\Component\Console\Application
    calls:
      - [ add, ["@LocationCommand"]]

  LocationCommand:
    class: Nachinius\Command\LocationCommand
    arguments: ["@HtmlGetter","get","@service_container"]
  HtmlGetter:
    class: Nachinius\Command\Components\HtmlGetter
    arguments: ["@HttpGetter","@cache"]
  HttpGetter:
    class: Nachinius\Command\Components\HttpGetter
  cache:
    alias: zendCacheAdapter

# using an almost trivial cache
  SimpleFSCache:
    class: Nachinius\Command\Components\SimpleFSCache
    arguments: ["%app.root_dir%/../data","@fs"]
  fs:
    class: Symfony\Component\Filesystem\Filesystem
  
# using the zend cache filesystem
  zendCacheAdapter:
    class: Nachinius\Command\Components\ZendCacheAdapter
    arguments: [ "@zendCache"]
  zendCache: 
    class: Zend\Cache\Storage\Adapter\Filesystem
    calls:
      - [ setOptions,  [ {"cache_dir": "%app.root_dir%/../cache/zend-cache-fs", "key_pattern": /^[a-z0-9_\+\-.]*$/Di } ]]
 